### ISSUE TITLE
Reservierung erstellen -  neuen Kunden anlegen

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#102]
Wenn man einen neuen Kunden während der Reservierung anlegen will, kommt einen Exception aufgrund der Validierung in der CustomerNewPanel.html
![reservierung erstellen - neuen kunden anlegen](https://cloud.githubusercontent.com/assets/15790924/12076353/9c881548-b1a8-11e5-92b2-278583a2e2a9.PNG)

Unexpected RuntimeException

Last cause: Component [discount] (path = [32:reservationContentComponent:customer_new:discount]) must be applied to a tag with [type] attribute matching any of [number], not [null]

Markup

The problem is in "file:/C:/workspaceSE/uni-sese_ws15/target/classes/org/scrum1/sese/view/page/panels/CustomerNewPanel.html":

<input wicket:id="discount" id="regDiscount" placeholder="0" class="form-control"/>

Stacktrace

Root cause:

Component [discount] (path = [32:reservationContentComponent:customer_new:discount]) must be applied to a tag with [type] attribute matching any of [number], not [null]
 MarkupStream: [markup = file:/C:/workspaceSE/uni-sese_ws15/target/classes/org/scrum1/sese/view/page/panels/CustomerNewPanel.html
<input wicket:id="discount" id="regDiscount" placeholder="0" class="form-control"/>, index = 0, current =  '<input wicket:id="discount" id="regDiscount" placeholder="0" class="form-control"/>' (line 0, column 0)]
     at org.apache.wicket.markup.MarkupStream.throwMarkupException(MarkupStream.java:526)
     at org.apache.wicket.Component.checkComponentTagAttribute(Component.java:3606)
     at org.apache.wicket.markup.html.form.TextField.onComponentTag(TextField.java:98)
     at org.apache.wicket.markup.html.form.NumberTextField.onComponentTag(NumberTextField.java:232)
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2521)
     at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
     at org.apache.wicket.Component.internalRender(Component.java:2380)
     at org.apache.wicket.Component.render(Component.java:2308)
     at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
     at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
     at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1434)
     at org.apache.wicket.MarkupContainer.onComponentTagBody(MarkupContainer.java:1357)
     at org.apache.wicket.markup.html.form.Form.onComponentTagBody(Form.java:1705)
     at org.apache.wicket.markup.html.panel.DefaultMarkupSourcingStrategy.onComponentTagBody(DefaultMarkupSourcingStrategy.java:70)
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
     at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
     at org.apache.wicket.Component.internalRender(Component.java:2380)
     at org.apache.wicket.Component.render(Component.java:2308)
     at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
     at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
     at org.apache.wicket.MarkupContainer.renderComponentTagBody(MarkupContainer.java:1434)
     at org.apache.wicket.MarkupContainer.renderAssociatedMarkup(MarkupContainer.java:703)
     at org.apache.wicket.markup.html.panel.AssociatedMarkupSourcingStrategy.renderAssociatedMarkup(AssociatedMarkupSourcingStrategy.java:77)
     at org.apache.wicket.markup.html.panel.PanelMarkupSourcingStrategy.onComponentTagBody(PanelMarkupSourcingStrategy.java:112)
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2565)
     at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1398)
     at org.apache.wicket.Component.internalRender(Component.java:2380)
     at org.apache.wicket.Component.render(Component.java:2308)
     at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1262)
     at org.apache.wicket.MarkupContainer.renderAll(MarkupContainer.java:1459)
     at org.apache.wicket.Page.onRender(Page.java:879)
     at org.apache.wicket.markup.html.WebPage.onRender(WebPage.java:141)
     at org.apache.wicket.Component.internalRender(Component.java:2380)
     at org.apache.wicket.Component.render(Component.java:2308)
     at org.apache.wicket.Page.renderPage(Page.java:1018)
     at org.apache.wicket.request.handler.render.WebPageRenderer.renderPage(WebPageRenderer.java:124)
     at org.apache.wicket.request.handler.render.WebPageRenderer.respond(WebPageRenderer.java:236)
     at org.apache.wicket.core.request.handler.RenderPageRequestHandler.respond(RenderPageRequestHandler.java:175)
     at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:865)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
     at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:97)
     at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
     at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
     at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
     at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
     at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
     at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
     at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
     at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
     at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
     at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
     at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
     at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
     at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
     at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
     at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
     at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
     at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
     at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
     at java.lang.Thread.run(Thread.java:745)

display page view

**Comment by develope80** [comment]
CustomerForm.java wird auch von CustomerNewPanel.java verwendet
* => CustomerNewPanel.html muss aktualisiert werden
* => auch hier benötigen wir Pflichfelder 
* => Validierung notwendig

**Comment by develope80** [comment]
Review/QA => OK
