### ISSUE TITLE
Zimmer suchen

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#97]
1) Sucht man nach Zimmern, so kommt es manchmal zu folgender Exception:

Root cause:

org.apache.wicket.WicketRuntimeException: The model of Select component [8:search_form:searchType] is not of type java.util.Collection, but more then one SelectOption component has been selected. Either remove the multiple attribute from the select tag or make the model of the Select component a collection
     at org.apache.wicket.extensions.markup.html.form.select.Select.convertInput(Select.java:148)
     at org.apache.wicket.markup.html.form.FormComponent.validate(FormComponent.java:1130)
     at org.apache.wicket.markup.html.form.Form$18.validate(Form.java:1948)
     at org.apache.wicket.markup.html.form.Form$ValidationVisitor.component(Form.java:177)
     at org.apache.wicket.markup.html.form.Form$ValidationVisitor.component(Form.java:161)
     at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:274)
     at org.apache.wicket.util.visit.Visits.visitPostOrderHelper(Visits.java:262)
     at org.apache.wicket.util.visit.Visits.visitPostOrder(Visits.java:245)
     at org.apache.wicket.markup.html.form.FormComponent.visitFormComponentsPostOrder(FormComponent.java:382)

**Comment by develope80** [comment]
#86 ist der selbe Bug
